enum MENU_OPTIONS {
  CREATE_COMPONENT = 1,
  CREATE_TESTS = 2,
  REACT_COMPONENT_FOLDER_AND_FILES = 3,
  REACT_COMPONENT_FILES_ONLY = 4,
  // FUNCTION
  CREATE_FUNC_TEST = 5,
  CREATE_FUNC_EXT_JS = 'js',
  CREATE_FUNC_EXT_TS = 'ts',
  // RECOIL
  CREATE_RECOIL_STATE = 6,
  RECOIL_STATE_FOLDER_AND_FILES = 7,
  RECOIL_STATE_FOLDER_AND_FILES_ONLY = 8,
  // JOTAI
  CREATE_JOTAI_STATE = 9,
  JOTAI_STATE_FOLDER_AND_FILES = 10,
  JOTAI_STATE_FOLDER_AND_FILES_ONLY = 11,
  JOTAI_STATE_WITH_RESET = 12,
  JOTAI_STATE_WITH_ATOM_FAMILY = 13,

  // ICONS
  INSERT_ICONS = 14,
}

export default MENU_OPTIONS;
