enum MENU_OPTIONS {
  CREATE_COMPONENT = 1,
  CREATE_TESTS = 2,
  REACT_COMPONENT_FOLDER_AND_FILES = 3,
  REACT_COMPONENT_FILES_ONLY = 4,
  CREATE_FUNC_TEST = 5,
  CREATE_FUNC_EXT_JS = 'js',
  CREATE_FUNC_EXT_TS = 'ts',
  CREATE_STATE = 6,
  STATE_FOLDER_AND_FILES = 7,
  STATE_FOLDER_AND_FILES_ONLY = 8
};

export default MENU_OPTIONS;