name: Deploy Extension in VSCode
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.head_commit.message, 'run:publish')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'npm'   # cache para npm

      - name: Install dependencies
        run: npm ci       # usa npm clean install

      - name: Instalar `vsce`
        run: npm i -g @vscode/vsce

      - name: Packaging the extension
        run: vsce package --no-dependencies

      - name: Publish on the Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Bump version (only after success)
        if: ${{ success() }}
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          npm version patch --message "v%s"
          git push origin main --follow-tags --force

      - name: Output version change
        if: ${{ success() }}
        run: npm pkg get version
